// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXwlpIZXQ_ez8LqGdJBFOT_TqKrTDjWw',
    appId: '1:629344566477:android:67e75202a7dc4fc4ecbd84',
    messagingSenderId: '629344566477',
    projectId: 'pzdeals-b9228',
    storageBucket: 'pzdeals-b9228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVM58K7j8-JsCFEzMnlvShtujaBeMHiTs',
    appId: '1:629344566477:ios:e5ab56422921f0fcecbd84',
    messagingSenderId: '629344566477',
    projectId: 'pzdeals-b9228',
    storageBucket: 'pzdeals-b9228.appspot.com',
    androidClientId: '629344566477-2731av9mf7j5pti8damtohc0k4vohg27.apps.googleusercontent.com',
    iosClientId: '629344566477-uaqec3u8dn4slk9jchpp761h31rblpgl.apps.googleusercontent.com',
    iosBundleId: 'com.kodecraft.pzdeals',
  );

}